// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// TODO: With JavaScript, get the date and send it with hx-vals
func AddLessonForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"add-lesson-form\" class=\"flex flex-col self-center items-center w-sm bg-gray-50 rounded-sm\"><label for=\"topic-input\">Tema de la lección</label> <input type=\"text\" name=\"topic\" id=\"topic-input\" class=\"border rounded-sm\"> <label for=\"aoc-input\">Cantidad de cartas (Podrás agregar más después)</label> <input type=\"number\" name=\"amount_of_cards\" id=\"aoc-input\" class=\"border rounded-sm\"> <label for=\"repetitions-input\" class=\"text-center\">Repeticiones deseadas (No se prodrá cambiar en el futuro)</label> <input type=\"number\" name=\"repetitions\" id=\"repetitions-input\" class=\"border rounded-sm\"> <button hx-post=\"/lesson/add\" type=\"submit\" class=\"bg-blue-400 w-fit rounded-xs self-center px-2 my-1.5\">Enviar</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
