-- +goose Up
CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
access_token TEXT UNIQUE,
api_key TEXT UNIQUE,
showed INTEGER NOT NULL
) ;
-- +goose Down
DELETE FROM users ;
DROP TABLE users ;
